name: Check

on: [pull_request, workflow_call]

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: golang
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git
        # Make sure the runner has access to the internal repos repo using an access token
        run: git config --global url."https://${{ secrets.CI_PROTOBUF_ACCESS }}@github.com/thinkparq".insteadOf https://github.com/thinkparq
      - name: Install toolchains and tools
        run: make install-tools
      - name: Run checks
        run: make check-gofmt check-linters check-go-tidy
      - name: Run tests
        run: make test-unit
